@startuml activity
skinparam defaultTextAlignment center
skinparam WrapWidth 180
skinparam MaxMessageSize 150
title Процесс создания страховки для кредитного продукта

|User|
start
:Инициировать создание страховки;

|Frontend|
:Отправить запрос на создание страховки;

|API Gateway|
:Получить запрос от пользователя;
:Проверить работоспособность сервиса страхования;

|Insurance Service|
:Передача статуса доступности;

|API Gateway|
if (Сервис страхования не доступен?) then (да)
  :Сформировать ответ ошибки 429;
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|API Gateway|
:Проверить работоспособность сервиса оплаты;

|Payment Service|
:Передача статуса доступности;

|API Gateway|
if (Сервис оплаты не доступен?) then (да)
  :Сформировать ответ ошибки 429;
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|API Gateway|
:Проверить работоспособность Bank API;

|BankAPI|
:Проверить работоспособность;

|API Gateway|
if (Банковское API не доступно?) then (да)
  :Сформировать ответ ошибки 429;
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|API Gateway|
:Отправить запрос на создание страховки в сервис страхования;

|Insurance Service|
:Проверить идемпотентность запроса;
note right 
Потребление событий из Kafka\n(проверка, 
не обрабатывался ли уже этот запрос)
end note

|Kafka|
:Передача данных о наличии события создания страхования;

|Insurance Service|
if (Идемпотентность не подтверждена?) then (да)
  :Сформировать ошибку 409 (конфликт);
  |API Gateway|
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|Insurance Service|
:Проверить авторизацию пользователя;
note right 
Потребление события из 
Kafka\n(валидация JWT-токена)
end note

|Kafka|
:Событие авторизации;

|Insurance Service|
if (Пользователь не авторизован?) then (да)
  :Сформировать ошибку 401;
  |API Gateway|
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|Insurance Service|
:Проверить права пользователя;
note right 
Чтение из ReadOnly Database\n
(копия оригинальной БД для чтения)
end note

|ReadOnly Database|
:Проверка прав пользователя;

|Insurance Service|
if (Права отсутствуют?) then (да)
  :Сформировать ошибку 403;
  |API Gateway|
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|Insurance Service|
:Проверить существование кредитного продукта;

|BankAPI|
:Передача информации о существовании;

|Insurance Service|
if (Кредитный продукт не существует?) then (да)
  :Сформировать ошибку 404;
  |API Gateway|
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|Insurance Service|
:Запросить базовую ставку кредита в BankAPI;

|BankAPI|
:Вернуть текущую ставку;

|Insurance Service|
:Рассчитать новую ставку со страховкой;

:Сформировать предложение (инверсный вариант);
:Передать предложение в API Gateway;

|API Gateway|
:Передать предложение во Frontend;

|Frontend|
:Показать пользователю предложение;

|User|
:Просмотреть предложение;
:Выбрать: согласиться на инверсный вариант?;

|Frontend|
:Передать выбор пользователя в API Gateway;

|API Gateway|
:Передать выбор в Insurance Service;

|Insurance Service|
if (Клиент соглашается на инверсный вариант?) then (да)
  :Создать финальную форму для заполнения;
  :Передать запрос на оплату страховки в сервис оплаты;
  |Payment Service|
  :Сформировать оплату;
  :Передать запрос на оплату во внешний платежный сервис;
  |Stripe|
  :Выставить и принять оплату;
  |Payment Service|
  :Передать данные об оплате в сервис страхования;
  |Insurance Service|
  if (Оплата не успешна?) then (да)
    :Сформировать ошибку оплаты;
    |API Gateway|
    :Передать ошибку во Frontend;
    |Frontend|
    :Показать ошибку пользователю;
    |User|
    :Получить результат;
    stop
  endif
  
  |Insurance Service|
  :Оформить страхование;
  :Записать данные в базу;
  |Database|
  :Запись данных о страховании;
  |Insurance Service|
  fork
    |Insurance Service|
    :Сформировать успешный ответ;
    |API Gateway|
    :Передать результат во Frontend;
    |Frontend|
    :Показать результат пользователю;
    |User|
    :Получить ошибку;
  fork again
    |Insurance Service|
    :Публиковать событие в Kafka;
    |Kafka|
    :Событие опубликовано;
  end fork
  stop
else (заемщик не соглашается на инверсный вариант)
  |Insurance Service|
  :Запросить расширенный риск-скоринг клиента;

  |BankAPI|
  :Передать коэффициент в Insurance Service;

  |Insurance Service|
  :Сформировать набор доступных предложений;
endif

|Insurance Service|
:Собрать все варианты в единую форму предложения (Offer);
:Передать предложение в API Gateway;

|API Gateway|
:Передать предложение во Frontend;

|Frontend|
:Показать пользователю варианты с ценами и условиями;

|User|
:Выбрать подходящий вариант;

|Frontend|
:Передать выбранный вариант в API Gateway;

|API Gateway|
:Передать выбор в Insurance Service;

|Insurance Service|
if (Выбран вариант с повышенным риском?) then (да)
  :Запросить у пользователя усиленное согласие (check-box);
  |API Gateway|
  :Передать запрос во Frontend;
  |Frontend|
  :Показать пользователю запрос на усиленное согласие;
  |User|
  :Подтвердить усиленное согласие;
  |Frontend|
  :Передать подтверждение в API Gateway;
  |API Gateway|
  :Передать подтверждение в Insurance Service;
endif

|Insurance Service|
:Создать финальную форму для заполнения (на основе выбранного варианта);
:Передать запрос на оплату страховки в сервис оплаты с суммой выбранного варианта;
|Payment Service|
:Сформировать оплату;
:Передать запрос на оплату во внешний платежный сервис;
|Stripe|
:Выставить и принять оплату;
|Payment Service|
:Передать данные об оплате в сервис страхования;
|Insurance Service|
if (Оплата НЕ успешна?) then (да)
  :Сформировать ошибку оплаты;
  |API Gateway|
  :Передать ошибку во Frontend;
  |Frontend|
  :Показать ошибку пользователю;
  |User|
  :Получить результат;
  stop
endif

|Insurance Service|
:Оформить страхование кредитного продукта;
:Записать данные в базу данных;
note right 
Запись в основную Database (write) 
с пометкой выбранной франшизы
end note
|Database|
:Запись данных о страховании;
|Insurance Service|
fork
  :Сформировать успешный ответ;
  |API Gateway|
  :Передать результат во Frontend;
  |Frontend|
  :Показать результат пользователю;
fork again
  :Публиковать событие о создании страховки в Kafka;
  |Kafka|
  :Событие опубликовано;
end fork
stop

@enduml
